In [1]:
!pip install lxml

Requirement already satisfied: lxml in c:\programdata\anaconda3\lib\site-packages (4.2.5)

WARNING: You are using pip version 20.0.2; however, version 20.2.2 is available.
You should consider upgrading via the 'c:\programdata\anaconda3\python.exe -m pip install --upgrade pip' command.

In [2]:
import pandas as pd

In [3]:
html_string = """
<table>
    <thead>
      <tr>
        <th>Order date</th>
        <th>Region</th> 
        <th>Item</th>
        <th>Units</th>
        <th>Unit cost</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>1/6/2018</td>
        <td>East</td> 
        <td>Pencil</td>
        <td>95</td>
        <td>1.99</td>
      </tr>
      <tr>
        <td>1/23/2018</td>
        <td>Central</td> 
        <td>Binder</td>
        <td>50</td>
        <td>19.99</td>
      </tr>
      <tr>
        <td>2/9/2018</td>
        <td>Central</td> 
        <td>Pencil</td>
        <td>36</td>
        <td>4.99</td>
      </tr>
      <tr>
        <td>3/15/2018</td>
        <td>West</td> 
        <td>Pen</td>
        <td>27</td>
        <td>19.99</td>
      </tr>
    </tbody>
</table>
"""

In [4]:
from IPython.core.display import display,HTML
display(HTML(html_string))

In [5]:
dfs = pd.read_html(html_string)

In [6]:
dfs

[  Order date   Region    Item  Units  Unit cost
 0   1/6/2018     East  Pencil     95       1.99
 1  1/23/2018  Central  Binder     50      19.99
 2   2/9/2018  Central  Pencil     36       4.99
 3  3/15/2018     West     Pen     27      19.99]

In [7]:
len(dfs)

1

In [9]:
df = dfs[0]
df

  Order date   Region    Item  Units  Unit cost
0   1/6/2018     East  Pencil     95       1.99
1  1/23/2018  Central  Binder     50      19.99
2   2/9/2018  Central  Pencil     36       4.99
3  3/15/2018     West     Pen     27      19.99

In [10]:
df.shape

(4, 5)

In [11]:
df.loc[df['Region']=='Central']

  Order date   Region    Item  Units  Unit cost
1  1/23/2018  Central  Binder     50      19.99
2   2/9/2018  Central  Pencil     36       4.99

In [12]:
df.loc[df['Units'] > 35]

  Order date   Region    Item  Units  Unit cost
0   1/6/2018     East  Pencil     95       1.99
1  1/23/2018  Central  Binder     50      19.99
2   2/9/2018  Central  Pencil     36       4.99

In [13]:
html_string = """
<table>
  <tr>
    <td>Order date</td>
    <td>Region</td> 
    <td>Item</td>
    <td>Units</td>
    <td>Unit cost</td>
  </tr>
  <tr>
    <td>1/6/2018</td>
    <td>East</td> 
    <td>Pencil</td>
    <td>95</td>
    <td>1.99</td>
  </tr>
  <tr>
    <td>1/23/2018</td>
    <td>Central</td> 
    <td>Binder</td>
    <td>50</td>
    <td>19.99</td>
  </tr>
  <tr>
    <td>2/9/2018</td>
    <td>Central</td> 
    <td>Pencil</td>
    <td>36</td>
    <td>4.99</td>
  </tr>
  <tr>
    <td>3/15/2018</td>
    <td>West</td> 
    <td>Pen</td>
    <td>27</td>
    <td>19.99</td>
  </tr>
</table>
"""

In [14]:
pd.read_html(html_string)[0]

            0        1       2      3          4
0  Order date   Region    Item  Units  Unit cost
1    1/6/2018     East  Pencil     95       1.99
2   1/23/2018  Central  Binder     50      19.99
3    2/9/2018  Central  Pencil     36       4.99
4   3/15/2018     West     Pen     27      19.99

In [17]:
pd.read_html(html_string, header=0)[0]

  Order date   Region    Item  Units  Unit cost
0   1/6/2018     East  Pencil     95       1.99
1  1/23/2018  Central  Binder     50      19.99
2   2/9/2018  Central  Pencil     36       4.99
3  3/15/2018     West     Pen     27      19.99

In [18]:
html_url = "https://www.basketball-reference.com/leagues/NBA_2019_per_game.html"

In [19]:
nba_tables = pd.read_html(html_url)

In [20]:
len(nba_tables)

1

In [21]:
nba_tables = nba_tables[0]

In [22]:
nba_tables.head()

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,Álex Abrines,SG,25,OKC,31,2,19.0,1.8,5.1,...,.923,0.2,1.4,1.5,0.6,0.5,0.2,0.5,1.7,5.3
1,2,Quincy Acy,PF,28,PHO,10,0,12.3,0.4,1.8,...,.700,0.3,2.2,2.5,0.8,0.1,0.4,0.4,2.4,1.7
2,3,Jaylen Adams,PG,22,ATL,34,1,12.6,1.1,3.2,...,.778,0.3,1.4,1.8,1.9,0.4,0.1,0.8,1.3,3.2
3,4,Steven Adams,C,25,OKC,80,80,33.4,6.0,10.1,...,.500,4.9,4.6,9.5,1.6,1.5,1.0,1.7,2.6,13.9
4,5,Bam Adebayo,C,21,MIA,82,28,23.3,3.4,5.9,...,.735,2.0,5.3,7.3,2.2,0.9,0.8,1.5,2.5,8.9

In [23]:
nba_tables.head(25)

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,Álex Abrines,SG,25,OKC,31,2,19.0,1.8,5.1,...,.923,0.2,1.4,1.5,0.6,0.5,0.2,0.5,1.7,5.3
1,2,Quincy Acy,PF,28,PHO,10,0,12.3,0.4,1.8,...,.700,0.3,2.2,2.5,0.8,0.1,0.4,0.4,2.4,1.7
2,3,Jaylen Adams,PG,22,ATL,34,1,12.6,1.1,3.2,...,.778,0.3,1.4,1.8,1.9,0.4,0.1,0.8,1.3,3.2
3,4,Steven Adams,C,25,OKC,80,80,33.4,6.0,10.1,...,.500,4.9,4.6,9.5,1.6,1.5,1.0,1.7,2.6,13.9
4,5,Bam Adebayo,C,21,MIA,82,28,23.3,3.4,5.9,...,.735,2.0,5.3,7.3,2.2,0.9,0.8,1.5,2.5,8.9
5,6,Deng Adel,SF,21,CLE,19,3,10.2,0.6,1.9,...,1.000,0.2,0.8,1.0,0.3,0.1,0.2,0.3,0.7,1.7
6,7,DeVaughn Akoon-Purcell,SG,25,DEN,7,0,3.1,0.4,1.4,...,.500,0.1,0.4,0.6,0.9,0.3,0.0,0.3,0.6,1.0
7,8,LaMarcus Aldridge,C,33,SAS,81,81,33.2,8.4,16.3,...,.847,3.1,6.1,9.2,2.4,0.5,1.3,1.8,2.2,21.3
8,9,Rawle Alkins,SG,21,CHI,10,1,12.0,1.3,3.9,...,.667,1.1,1.5,2.6,1.3,0.1,0.0,0.8,0.7,3.7
9,10,Grayson Allen,SG,23,UTA,38,2,10.9,1.8,4.7,...,.750,0.1,0.5,0.6,0.7,0.2,0.2,0.9,1.2,5.6
10,11,Jarrett Allen,C,20,BRK,80,80,26.2,4.2,7.1,...,.709,2.4,6.0,8.4,1.4,0.5,1.5,1.3,2.3,10.9
11,12,Kadeem Allen,SG,26,NYK,19,1,21.9,3.4,7.4,...,.778,0.4,2.3,2.7,4.0,0.8,0.2,1.4,2.4,9.9
12,13,Al-Farouq Aminu,PF,28,POR,81,81,28.3,3.2,7.3,...,.867,1.4,6.1,7.5,1.3,0.8,0.4,0.9,1.8,9.4
13,14,Justin Anderson,SF,25,ATL,48,4,9.6,1.3,3.3,...,.743,0.5,1.3,1.8,0.5,0.5,0.3,0.5,1.0,3.7
14,15,Kyle Anderson,SF,25,MEM,43,40,29.8,3.5,6.4,...,.578,1.1,4.7,5.8,3.0,1.3,0.9,1.3,2.6,8.0
15,16,Ryan Anderson,PF,30,TOT,25,8,12.9,0.8,2.8,...,.750,0.7,1.4,2.2,0.8,0.2,0.0,0.6,1.0,2.5
16,16,Ryan Anderson,PF,30,PHO,15,8,18.5,1.3,4.0,...,.786,0.9,2.1,3.0,1.1,0.2,0.1,0.8,1.5,3.7
17,16,Ryan Anderson,PF,30,MIA,10,0,4.4,0.2,0.9,...,.500,0.4,0.5,0.9,0.2,0.1,0.0,0.2,0.2,0.7
18,17,Ike Anigbogu,C,20,IND,3,0,2.0,0.0,1.0,...,NaN,0.3,0.7,1.0,0.3,0.0,0.3,0.3,0.0,0.0
19,18,Giannis Antetokounmpo,PF,24,MIL,72,72,32.8,10.0,17.3,...,.729,2.2,10.3,12.5,5.9,1.3,1.5,3.7,3.2,27.7
20,19,Kostas Antetokounmpo,PF,21,DAL,2,0,5.5,0.0,1.5,...,.500,0.0,0.5,0.5,0.0,1.0,0.0,0.5,0.0,1.0
21,20,Carmelo Anthony,PF,34,HOU,10,2,29.4,4.9,12.1,...,.682,0.9,4.5,5.4,0.5,0.4,0.7,0.8,3.2,13.4
22,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
23,21,OG Anunoby,SF,21,TOR,67,6,20.2,2.7,6.0,...,.581,0.9,2.1,2.9,0.7,0.7,0.3,0.8,2.1,7.0
24,22,Ryan Arcidiacono,PG,24,CHI,81,32,24.2,2.3,5.2,...,.873,0.3,2.4,2.7,3.3,0.8,0.0,0.8,2.1,6.7

In [29]:
nba_tables.drop(range(23,df.shape[0]+1,20))

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,Álex Abrines,SG,25,OKC,31,2,19.0,1.8,5.1,...,.923,0.2,1.4,1.5,0.6,0.5,0.2,0.5,1.7,5.3
1,2,Quincy Acy,PF,28,PHO,10,0,12.3,0.4,1.8,...,.700,0.3,2.2,2.5,0.8,0.1,0.4,0.4,2.4,1.7
2,3,Jaylen Adams,PG,22,ATL,34,1,12.6,1.1,3.2,...,.778,0.3,1.4,1.8,1.9,0.4,0.1,0.8,1.3,3.2
3,4,Steven Adams,C,25,OKC,80,80,33.4,6.0,10.1,...,.500,4.9,4.6,9.5,1.6,1.5,1.0,1.7,2.6,13.9
4,5,Bam Adebayo,C,21,MIA,82,28,23.3,3.4,5.9,...,.735,2.0,5.3,7.3,2.2,0.9,0.8,1.5,2.5,8.9
5,6,Deng Adel,SF,21,CLE,19,3,10.2,0.6,1.9,...,1.000,0.2,0.8,1.0,0.3,0.1,0.2,0.3,0.7,1.7
6,7,DeVaughn Akoon-Purcell,SG,25,DEN,7,0,3.1,0.4,1.4,...,.500,0.1,0.4,0.6,0.9,0.3,0.0,0.3,0.6,1.0
7,8,LaMarcus Aldridge,C,33,SAS,81,81,33.2,8.4,16.3,...,.847,3.1,6.1,9.2,2.4,0.5,1.3,1.8,2.2,21.3
8,9,Rawle Alkins,SG,21,CHI,10,1,12.0,1.3,3.9,...,.667,1.1,1.5,2.6,1.3,0.1,0.0,0.8,0.7,3.7
9,10,Grayson Allen,SG,23,UTA,38,2,10.9,1.8,4.7,...,.750,0.1,0.5,0.6,0.7,0.2,0.2,0.9,1.2,5.6
10,11,Jarrett Allen,C,20,BRK,80,80,26.2,4.2,7.1,...,.709,2.4,6.0,8.4,1.4,0.5,1.5,1.3,2.3,10.9
11,12,Kadeem Allen,SG,26,NYK,19,1,21.9,3.4,7.4,...,.778,0.4,2.3,2.7,4.0,0.8,0.2,1.4,2.4,9.9
12,13,Al-Farouq Aminu,PF,28,POR,81,81,28.3,3.2,7.3,...,.867,1.4,6.1,7.5,1.3,0.8,0.4,0.9,1.8,9.4
13,14,Justin Anderson,SF,25,ATL,48,4,9.6,1.3,3.3,...,.743,0.5,1.3,1.8,0.5,0.5,0.3,0.5,1.0,3.7
14,15,Kyle Anderson,SF,25,MEM,43,40,29.8,3.5,6.4,...,.578,1.1,4.7,5.8,3.0,1.3,0.9,1.3,2.6,8.0
15,16,Ryan Anderson,PF,30,TOT,25,8,12.9,0.8,2.8,...,.750,0.7,1.4,2.2,0.8,0.2,0.0,0.6,1.0,2.5
16,16,Ryan Anderson,PF,30,PHO,15,8,18.5,1.3,4.0,...,.786,0.9,2.1,3.0,1.1,0.2,0.1,0.8,1.5,3.7
17,16,Ryan Anderson,PF,30,MIA,10,0,4.4,0.2,0.9,...,.500,0.4,0.5,0.9,0.2,0.1,0.0,0.2,0.2,0.7
18,17,Ike Anigbogu,C,20,IND,3,0,2.0,0.0,1.0,...,NaN,0.3,0.7,1.0,0.3,0.0,0.3,0.3,0.0,0.0
19,18,Giannis Antetokounmpo,PF,24,MIL,72,72,32.8,10.0,17.3,...,.729,2.2,10.3,12.5,5.9,1.3,1.5,3.7,3.2,27.7
20,19,Kostas Antetokounmpo,PF,21,DAL,2,0,5.5,0.0,1.5,...,.500,0.0,0.5,0.5,0.0,1.0,0.0,0.5,0.0,1.0
21,20,Carmelo Anthony,PF,34,HOU,10,2,29.4,4.9,12.1,...,.682,0.9,4.5,5.4,0.5,0.4,0.7,0.8,3.2,13.4
22,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
23,21,OG Anunoby,SF,21,TOR,67,6,20.2,2.7,6.0,...,.581,0.9,2.1,2.9,0.7,0.7,0.3,0.8,2.1,7.0
24,22,Ryan Arcidiacono,PG,24,CHI,81,32,24.2,2.3,5.2,...,.873,0.3,2.4,2.7,3.3,0.8,0.0,0.8,2.1,6.7
25,23,Trevor Ariza,SF,33,TOT,69,69,34.0,4.3,10.7,...,.793,0.7,4.7,5.4,3.7,1.3,0.3,1.5,1.9,12.5
26,23,Trevor Ariza,SF,33,PHO,26,26,34.0,3.3,8.7,...,.837,0.6,5.0,5.6,3.3,1.5,0.3,1.5,1.7,9.9
27,23,Trevor Ariza,SF,33,WAS,43,43,34.1,4.8,11.8,...,.777,0.8,4.5,5.3,3.8,1.2,0.3,1.6,2.0,14.1
28,24,D.J. Augustin,PG,31,ORL,81,81,28.0,3.9,8.4,...,.866,0.5,2.0,2.5,5.3,0.6,0.0,1.6,1.4,11.7
29,25,Deandre Ayton,C,20,PHO,71,70,30.7,7.2,12.3,...,.746,3.1,7.1,10.3,1.8,0.9,0.9,1.8,2.9,16.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
704,510,Andrew Wiggins,SF,23,MIN,73,73,34.8,6.8,16.6,...,.699,1.1,3.7,4.8,2.5,1.0,0.7,1.9,2.1,18.1
705,511,Alan Williams,PF,26,BRK,5,0,5.2,1.6,2.6,...,.500,0.8,3.0,3.8,0.6,0.2,0.0,0.2,0.4,3.6
706,512,C.J. Williams,SG,28,MIN,15,0,8.5,1.1,2.3,...,.000,0.1,0.5,0.5,0.8,0.4,0.0,0.3,1.1,2.6
707,513,Johnathan Williams,C,23,LAL,24,0,15.5,2.7,4.6,...,.563,2.0,2.1,4.1,0.5,0.3,0.3,0.7,2.6,6.5
708,514,Kenrich Williams,SF,24,NOP,46,29,23.5,2.3,6.1,...,.684,1.2,3.6,4.8,1.8,1.0,0.4,0.8,2.1,6.1
709,515,Lou Williams,SG,32,LAC,75,1,26.6,6.5,15.2,...,.876,0.5,2.4,3.0,5.4,0.8,0.1,2.4,1.1,20.0
710,516,Marvin Williams,PF,32,CHO,75,75,28.4,3.7,8.7,...,.767,1.0,4.4,5.4,1.2,0.9,0.8,0.6,2.1,10.1
711,517,Robert Williams,C,21,BOS,32,2,8.8,1.1,1.6,...,.600,0.8,1.7,2.5,0.2,0.3,1.3,0.3,1.1,2.5
712,518,Troy Williams,SF,24,SAC,21,0,14.9,2.1,4.7,...,.600,0.6,2.2,2.8,0.5,0.5,0.4,0.4,1.8,5.3
713,519,D.J. Wilson,PF,22,MIL,48,3,18.4,2.2,5.2,...,.553,0.9,3.7,4.6,1.1,0.4,0.4,0.7,1.8,5.8
714,520,Justise Winslow,SF,22,MIA,66,52,29.7,4.9,11.3,...,.628,1.0,4.4,5.4,4.3,1.1,0.3,2.2,2.7,12.6
715,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
716,521,Christian Wood,PF,23,TOT,21,2,12.0,2.9,5.6,...,.732,0.8,3.1,4.0,0.4,0.3,0.5,0.8,0.8,8.2
717,521,Christian Wood,PF,23,MIL,13,0,4.8,0.9,1.9,...,.667,0.3,1.2,1.5,0.2,0.0,0.0,0.2,0.2,2.8
718,521,Christian Wood,PF,23,NOP,8,2,23.6,6.1,11.5,...,.756,1.6,6.3,7.9,0.8,0.9,1.3,1.8,1.8,16.9
719,522,Delon Wright,PG,26,TOT,75,13,22.7,3.2,7.4,...,.793,0.9,2.6,3.5,3.3,1.2,0.4,1.0,1.4,8.7
720,522,Delon Wright,PG,26,TOR,49,2,18.3,2.6,6.0,...,.869,0.8,1.8,2.6,2.2,0.9,0.3,0.8,1.1,6.9
721,522,Delon Wright,PG,26,MEM,26,11,30.8,4.4,10.2,...,.742,1.1,4.3,5.4,5.3,1.6,0.6,1.5,1.9,12.2
722,523,Guerschon Yabusele,PF,23,BOS,41,1,6.1,0.9,1.9,...,.682,0.6,0.7,1.3,0.4,0.2,0.2,0.4,0.8,2.3
723,524,Nick Young,SG,33,DEN,4,0,9.3,0.8,2.3,...,NaN,0.0,0.3,0.3,0.5,0.0,0.3,0.5,1.0,2.3
724,525,Thaddeus Young,PF,30,IND,81,81,30.7,5.5,10.4,...,.644,2.4,4.1,6.5,2.5,1.5,0.4,1.5,2.4,12.6
725,526,Trae Young,PG,20,ATL,81,81,30.9,6.5,15.5,...,.829,0.8,2.9,3.7,8.1,0.9,0.2,3.8,1.7,19.1
726,527,Cody Zeller,C,26,CHO,49,47,25.4,3.9,7.0,...,.787,2.2,4.6,6.8,2.1,0.8,0.8,1.3,3.3,10.1
727,528,Tyler Zeller,C,29,TOT,6,1,15.5,2.7,5.0,...,.778,1.8,2.2,4.0,0.7,0.2,0.5,0.7,3.3,7.7
728,528,Tyler Zeller,C,29,ATL,2,0,5.5,0.0,1.0,...,NaN,1.0,2.0,3.0,0.5,0.0,0.0,0.0,2.0,0.0
729,528,Tyler Zeller,C,29,MEM,4,1,20.5,4.0,7.0,...,.778,2.3,2.3,4.5,0.8,0.3,0.8,1.0,4.0,11.5
730,529,Ante Žižić,C,22,CLE,59,25,18.3,3.1,5.6,...,.705,1.8,3.6,5.4,0.9,0.2,0.4,1.0,1.9,7.8
731,530,Ivica Zubac,C,21,TOT,59,37,17.6,3.6,6.4,...,.802,1.9,4.2,6.1,1.1,0.2,0.9,1.2,2.3,8.9
732,530,Ivica Zubac,C,21,LAL,33,12,15.6,3.4,5.8,...,.864,1.6,3.3,4.9,0.8,0.1,0.8,1.0,2.2,8.5
733,530,Ivica Zubac,C,21,LAC,26,25,20.2,3.8,7.2,...,.733,2.3,5.3,7.7,1.5,0.4,0.9,1.4,2.5,9.4

In [30]:
import requests

html_url = "https://en.wikipedia.org/wiki/The_Simpsons"

In [32]:
r = requests.get(html_url)

wiki_tables = pd.read_html(r.text, header=0)

In [33]:
len(wiki_tables)

27

In [34]:
simpsons = wiki_tables[1]

In [35]:
simpsons.head()

,Season,No. ofepisodes,Originally aired,Viewership,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,Season premiere,Season finale,Time Slot (ET),Avg. viewers(in millions),Most watched episode,NaN,NaN,NaN,NaN
1,Viewers(millions),Episode Title,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,1989–90,13,"December 17, 1989","May 13, 1990",Sunday 8:30 pm,27.8,33.5,"""Life on the Fast Lane"""
3,2,1990–91,22,"October 11, 1990","July 11, 1991",Thursday 8:00 pm,24.4,33.6,"""Bart Gets an F"""
4,3,1991–92,24,"September 19, 1991","August 27, 1992",21.8,25.5,"""Colonel Homer""",NaN

In [36]:
simpsons.drop([0, 1], inplace=True)

In [37]:
simpsons.head()

,Season,No. ofepisodes,Originally aired,Viewership,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
2,1,1989–90,13,"December 17, 1989","May 13, 1990",Sunday 8:30 pm,27.8,33.5,"""Life on the Fast Lane"""
3,2,1990–91,22,"October 11, 1990","July 11, 1991",Thursday 8:00 pm,24.4,33.6,"""Bart Gets an F"""
4,3,1991–92,24,"September 19, 1991","August 27, 1992",21.8,25.5,"""Colonel Homer""",NaN
5,4,1992–93,22,"September 24, 1992","May 13, 1993",22.4,28.6,"""Lisa's First Word""",NaN
6,5,1993–94,22,"September 30, 1993","May 19, 1994",18.9,24.0,"""Treehouse of Horror IV""",NaN

In [38]:
simpsons.set_index('Season')

,No. ofepisodes,Originally aired,Viewership,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
Season,,,,,,,,
1,1989–90,13,"December 17, 1989","May 13, 1990",Sunday 8:30 pm,27.8,33.5,"""Life on the Fast Lane"""
2,1990–91,22,"October 11, 1990","July 11, 1991",Thursday 8:00 pm,24.4,33.6,"""Bart Gets an F"""
3,1991–92,24,"September 19, 1991","August 27, 1992",21.8,25.5,"""Colonel Homer""",NaN
4,1992–93,22,"September 24, 1992","May 13, 1993",22.4,28.6,"""Lisa's First Word""",NaN
5,1993–94,22,"September 30, 1993","May 19, 1994",18.9,24.0,"""Treehouse of Horror IV""",NaN
6,1994–95,25,"September 4, 1994","May 21, 1995",Sunday 8:00 pm,15.6,22.2,"""Treehouse of Horror V"""
7,1995–96,25,"September 17, 1995","May 19, 1996",15.1,19.7,"""Treehouse of Horror VI""",NaN
8,1996–97,25,"October 27, 1996","May 18, 1997",Sunday 8:30 pm (Episodes 1–3)Sunday 8:00 pm (E...,14.5,20.9,"""The Springfield Files"""
9,1997–98,25,"September 21, 1997","May 17, 1998",Sunday 8:00 pm,15.3,19.8,"""The Two Mrs. Nahasapeemapetilons"""
10,1998–99,23,"August 23, 1998","May 16, 1999",13.5,15.5,"""Maximum Homerdrive""",NaN
11,1999–2000,22,"September 26, 1999","May 21, 2000",8.8,18.4,"""The Mansion Family""",NaN
12,2000–01,21,"November 1, 2000","May 20, 2001",15.5,18.6,"""Worst Episode Ever""",NaN
13,2001–02,22,"November 6, 2001","May 22, 2002",Tuesday 8:30 pm (Episode 1)Sunday 8:00 pm (Epi...,12.5,14.9,"""The Parent Rap"""
14,2002–03,22,"November 3, 2002","May 18, 2003","Sunday 8:00 pm (Episodes 1–11, 13–21)Sunday 8:...",14.4,22.1,"""I'm Spelling as Fast as I Can"""
15,2003–04,22,"November 2, 2003","May 23, 2004",Sunday 8:00 pm,11.0,16.3,"""I, (Annoyed Grunt)-Bot"""
16,2004–05,21,"November 7, 2004","May 15, 2005","Sunday 8:00 pm (Episodes 1–7, 9–16, 18, 20)Sun...",10.2,23.07,"""Homer and Ned's Hail Mary Pass"""
17,2005–06,22,"September 11, 2005","May 21, 2006",Sunday 8:00 pm,9.55,11.63,"""Treehouse of Horror XVI"""
18,2006–07,22,"September 10, 2006","May 20, 2007",9.15,13.90,"""The Wife Aquatic""",NaN
19,2007–08,20,"September 23, 2007","May 18, 2008",8.37,11.7,"""Treehouse of Horror XVIII""",NaN
20,2008–09,21,"September 28, 2008","May 17, 2009",7.1,12.4,"""Treehouse of Horror XIX""",NaN
21,2009–10,23,"September 27, 2009","May 23, 2010",7.1,14.62,"""Once Upon a Time in Springfield""",NaN
22,2010–11,22,"September 26, 2010","May 22, 2011",7.09,12.6,"""Moms I'd Like to Forget""",NaN
23,2011–12,22,"September 25, 2011","May 20, 2012",6.15[149],11.48,"""The D'oh-cial Network""",NaN
24,2012–13,22,"September 30, 2012","May 19, 2013",5.41[150],8.97,"""Homer Goes to Prep School""",NaN
25,2013–14,22,"September 29, 2013","May 18, 2014",5.02[151],12.04,"""Steal This Episode""",NaN
26,2014–15,22,"September 28, 2014","May 17, 2015",5.61[152],10.62,"""The Man Who Came to Be Dinner""",NaN
27,2015–16,22,"September 27, 2015","May 22, 2016",4.0[153],8.33,"""Teenage Mutant Milk-Caused Hurdles""",NaN
28,2016–17,22,"September 25, 2016","May 21, 2017",4.80[154],8.19,"""Pork and Burns""",NaN
29,2017–18,21,"October 1, 2017","May 20, 2018",4.07[155],8.04,"""Frink Gets Testy""",NaN
30,2018–19,23,"September 30, 2018","May 12, 2019",3.10[156],8.20,"""The Girl on the Bus""",NaN
31,2019–20,22,"September 29, 2019","May 17, 2020",2.58[157],5.63,"""Go Big or Go Homer""",NaN
32,2020–21,TBA,"September 27, 2020",TBA,NaN,TBA,TBA,TBA

In [39]:
simpsons['No. ofepisodes'].unique()

array(['1989–90', '1990–91', '1991–92', '1992–93', '1993–94', '1994–95',
       '1995–96', '1996–97', '1997–98', '1998–99', '1999–2000', '2000–01',
       '2001–02', '2002–03', '2003–04', '2004–05', '2005–06', '2006–07',
       '2007–08', '2008–09', '2009–10', '2010–11', '2011–12', '2012–13',
       '2013–14', '2014–15', '2015–16', '2016–17', '2017–18', '2018–19',
       '2019–20', '2020–21'], dtype=object)

In [41]:
simpsons = simpsons.loc[simpsons['No. ofepisodes'] != 'TBA']
simpsons.head()

,Season,No. ofepisodes,Originally aired,Viewership,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
2,1,1989–90,13,"December 17, 1989","May 13, 1990",Sunday 8:30 pm,27.8,33.5,"""Life on the Fast Lane"""
3,2,1990–91,22,"October 11, 1990","July 11, 1991",Thursday 8:00 pm,24.4,33.6,"""Bart Gets an F"""
4,3,1991–92,24,"September 19, 1991","August 27, 1992",21.8,25.5,"""Colonel Homer""",NaN
5,4,1992–93,22,"September 24, 1992","May 13, 1993",22.4,28.6,"""Lisa's First Word""",NaN
6,5,1993–94,22,"September 30, 1993","May 19, 1994",18.9,24.0,"""Treehouse of Horror IV""",NaN

In [42]:
min_season = simpsons['No. ofepisodes'].min()

min_season

'1989–90'

In [43]:
simpsons.loc[simpsons['No. ofepisodes'] == min_season]

,Season,No. ofepisodes,Originally aired,Viewership,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
2,1,1989–90,13,"December 17, 1989","May 13, 1990",Sunday 8:30 pm,27.8,33.5,"""Life on the Fast Lane"""

In [44]:
simpsons.head()

,Season,No. ofepisodes,Originally aired,Viewership,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
2,1,1989–90,13,"December 17, 1989","May 13, 1990",Sunday 8:30 pm,27.8,33.5,"""Life on the Fast Lane"""
3,2,1990–91,22,"October 11, 1990","July 11, 1991",Thursday 8:00 pm,24.4,33.6,"""Bart Gets an F"""
4,3,1991–92,24,"September 19, 1991","August 27, 1992",21.8,25.5,"""Colonel Homer""",NaN
5,4,1992–93,22,"September 24, 1992","May 13, 1993",22.4,28.6,"""Lisa's First Word""",NaN
6,5,1993–94,22,"September 30, 1993","May 19, 1994",18.9,24.0,"""Treehouse of Horror IV""",NaN

In [45]:
simpsons.to_csv('out.csv')

In [46]:
pd.read_csv('out.csv', index_col='Season').head()

,Unnamed: 0,No. ofepisodes,Originally aired,Viewership,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
Season,,,,,,,,,
1,2,1989–90,13,"December 17, 1989","May 13, 1990",Sunday 8:30 pm,27.8,33.5,"""Life on the Fast Lane"""
2,3,1990–91,22,"October 11, 1990","July 11, 1991",Thursday 8:00 pm,24.4,33.6,"""Bart Gets an F"""
3,4,1991–92,24,"September 19, 1991","August 27, 1992",21.8,25.5,"""Colonel Homer""",NaN
4,5,1992–93,22,"September 24, 1992","May 13, 1993",22.4,28.6,"""Lisa's First Word""",NaN
5,6,1993–94,22,"September 30, 1993","May 19, 1994",18.9,24.0,"""Treehouse of Horror IV""",NaN